project_name: newrelic-client-go

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

build:
  skip: true

release:
  prerelease: false
  name_template: "{{.ProjectName}} v{{.Version}}"

